### ISSUE TITLE
能更新一下代码里的文件和路径吗？

### ISSUE THREAD

**Issue by Asphelzhn** [caidongqi/TaiTouLv_Jiance#2]
代码里有些文件和路径写死了，能更新一下配置的文件吗，感谢

**Comment by caidongqi** [comment]
过几天我会重新上传一份更完善的代码和readme，感谢关注

**Comment by caidongqi** [comment]
我已经更新了全部的代码，近日会再更新一下readme。

**Comment by Asphelzhn** [comment]
> 我已经更新了全部的代码，近日会再更新一下readme。

好的，非常感谢

**Comment by Asphelzhn** [comment]
> 我已经更新了全部的代码，近日会再更新一下readme。

期待更新readme

**Comment by caidongqi** [comment]
> > 我已经更新了全部的代码，近日会再更新一下readme。
> 
> 期待更新readme

我已经更新了README啦，本来还准备简单写一下人脸识别的技术原理的，不过想了一下网上已经有很多写的很详细、形象的帖子了，我就不再赘述啦（主要是懒哈哈哈）。

非常感谢你的关注~

**Comment by Asphelzhn** [comment]
> > > 我已经更新了全部的代码，近日会再更新一下readme。
> > 
> > 
> > 期待更新readme
> 
> 我已经更新了README啦，本来还准备简单写一下人脸识别的技术原理的，不过想了一下网上已经有很多写的很详细、形象的帖子了，我就不再赘述啦（主要是懒哈哈哈）。
> 
> 非常感谢你的关注~

非常感谢，readme写的很棒，用心了
